# Generated by Django 3.2.20 on 2023-08-31 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=500)),
                ('s_level', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=500)),
                ('r_email', models.CharField(max_length=500)),
                ('r_phone', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_office', models.CharField(max_length=500)),
                ('e_position', models.CharField(max_length=500)),
                ('e_duration', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_institution', models.CharField(max_length=500)),
                ('a_year', models.CharField(max_length=500)),
                ('a_award', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cv')),
            ],
        ),
    ]
