# Generated by Django 3.2.20 on 2023-08-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_academic_cv_experince_referee_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experince',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Cv',
        ),
        migrations.DeleteModel(
            name='Experince',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
