# Generated by Django 3.2.20 on 2023-09-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20230901_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('kepala_kemahasiswaan', 'kepala kemahasiswaan'), ('staf', 'Staf')], max_length=50),
        ),
    ]
