# Generated by Django 3.2.20 on 2023-09-01 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_user_type'),
        ('webbuser', '0004_auto_20230831_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilmahasiswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user_mahasiswa'),
        ),
    ]
