# Generated by Django 3.2.20 on 2023-09-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0005_alter_profilmahasiswa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbuser.personalinfo'),
        ),
    ]
