# Generated by Django 3.2.20 on 2023-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0006_alter_skill_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_skpi',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=20)),
                ('tempat', models.CharField(max_length=30)),
                ('tgl_lahir', models.DateField()),
                ('masuk', models.IntegerField()),
                ('lulus', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=20),
        ),
    ]
