# Generated by Django 3.2.20 on 2023-09-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0007_auto_20230901_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_skpi',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AlterField(
            model_name='data_skpi',
            name='lulus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_skpi',
            name='nim',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
