# Generated by Django 3.2.20 on 2023-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0008_auto_20230901_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_skpi',
            name='PA',
            field=models.CharField(default='default_value', max_length=300),
        ),
        migrations.AddField(
            model_name='data_skpi',
            name='ppi',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
