# Generated by Django 3.2.20 on 2023-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0009_auto_20230901_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_skpi',
            name='PA',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='data_skpi',
            name='ppi',
            field=models.CharField(max_length=200),
        ),
    ]
