# Generated by Django 3.2.20 on 2023-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0010_auto_20230901_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_skpi',
            name='foto',
            field=models.ImageField(null=True, upload_to='SKPI/'),
        ),
    ]
