# Generated by Django 3.2.20 on 2023-09-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0016_auto_20230901_2257'),
        ('webbuser', '0011_data_skpi_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_skpi',
            name='prodi',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.prodi'),
        ),
    ]
