# Generated by Django 3.2.20 on 2023-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0015_alter_data_skpi_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_skpi',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='SKPI/'),
        ),
    ]
