# Generated by Django 3.2.20 on 2023-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbuser', '0018_auto_20230902_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_skpi',
            name='prodi',
            field=models.CharField(choices=[('Teknik Informasi', 'Teknik Informasi'), ('Teknik Mekatronika', 'Teknik Mekatronika'), ('Teknologi Elektronika', 'Teknologi Elektronika'), ('Akuntansi', 'Akuntansi'), ('Akuntansi Sektor Publik', 'Akuntansi Sektor Publik')], max_length=90),
        ),
    ]
