# Generated by Django 3.2.20 on 2023-07-30 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0002_prestasi_prodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id_pelanggaran', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nim', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], max_length=20)),
                ('angkatan', models.IntegerField()),
                ('Jenis_pelanggaran', models.CharField(max_length=300)),
                ('sanksi', models.CharField(max_length=300)),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.prodi')),
            ],
        ),
    ]
