# Generated by Django 3.2.20 on 2023-07-30 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0003_pelanggaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Beasiswa',
            fields=[
                ('id_beasiswa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('dibuka', models.DateField()),
                ('ditutup', models.DateField()),
                ('benefit', models.TextField()),
                ('deskripsi', models.TextField()),
                ('persyaratan', models.TextField()),
                ('ip_minimal', models.IntegerField()),
                ('ipk_minimal', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='covers/')),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id_organisasi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisasi', models.CharField(max_length=100)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='organisasi/')),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penerima_Beasiswa',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('gender', models.CharField(choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('beasiswa', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa_Magang',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('angkatan', models.IntegerField()),
                ('gender', models.CharField(choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], max_length=20)),
                ('jalur_masuk', models.CharField(max_length=100)),
                ('tgl_magang', models.DateField()),
                ('perusahaan', models.CharField(max_length=300)),
                ('pembimbing', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=20)),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='Anggota_Organisasi',
            fields=[
                ('id_anggota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nim', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('laki-laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], max_length=20)),
                ('angkatan', models.IntegerField()),
                ('jabatan', models.CharField(max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='organisasi/anggota/')),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.organisasi')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.prodi')),
            ],
        ),
    ]
