# Generated by Django 3.2.20 on 2023-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0005_alter_artikel_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisasi',
            name='status',
            field=models.CharField(choices=[('akhtif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='akhtif', max_length=20),
        ),
    ]
