# Generated by Django 3.2.20 on 2023-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0006_organisasi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisasi',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=20),
        ),
    ]
