# Generated by Django 3.2.20 on 2023-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0009_alter_penerima_beasiswa_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='smtr_akhir',
        ),
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='smtr_awal',
        ),
        migrations.AlterField(
            model_name='penerima_beasiswa',
            name='nama',
            field=models.CharField(max_length=200),
        ),
    ]
