# Generated by Django 3.2.20 on 2023-08-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0013_penerima_beasiswa_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='beasiswa',
        ),
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='smstr_akhir',
        ),
        migrations.RemoveField(
            model_name='penerima_beasiswa',
            name='smstr_awal',
        ),
        migrations.CreateModel(
            name='Beasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beasiswa', models.CharField(max_length=200)),
                ('smstr_awal', models.CharField(max_length=80, null=True)),
                ('smstr_akhir', models.CharField(max_length=80, null=True)),
                ('id_beasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.penerima_beasiswa')),
            ],
        ),
    ]
