# Generated by Django 3.2.20 on 2023-08-30 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0014_auto_20230828_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='Deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
