# Generated by Django 3.2.20 on 2023-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0015_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodi',
            name='ka_prodi',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='prodi',
            name='nrp',
            field=models.IntegerField(default=0),
        ),
    ]
