# Generated by Django 3.2.20 on 2023-09-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0016_auto_20230901_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.category'),
        ),
    ]
