# Generated by Django 3.2.20 on 2023-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0018_auto_20230910_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_beasiswa',
            name='ip_minimal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='data_beasiswa',
            name='ipk_minimal',
            field=models.CharField(max_length=10),
        ),
    ]
