# Generated by Django 3.2.20 on 2023-10-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0020_alter_prodi_nrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodi',
            name='ka_prodi',
            field=models.CharField(max_length=100),
        ),
    ]
