# Generated by Django 3.2.20 on 2023-10-16 18:00

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0021_alter_prodi_ka_prodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan_PPI',
            fields=[
                ('id_perusahaan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_psh', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('kontak', models.CharField(max_length=20)),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
