# Generated by Django 3.2.20 on 2023-10-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0023_remove_mahasiswa_magang_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa_magang',
            name='perusahaan',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.perusahaan_ppi'),
        ),
    ]
